apiVersion: v2
name: rcloud
description: A Helm chart for Rcloud.
type: application
dependencies:
  - name: kratos
    version: 0.22.2
    repository: https://k8s.ory.sh/helm/charts
    condition: deploy.kratos.enable
  - name: elasticsearch
    version: 7.17.1
    repository: https://helm.elastic.co
    condition: deploy.elasticsearch.enable
  - name: postgresql
    version: 11.1.9
    repository: https://charts.bitnami.com/bitnami
    condition: deploy.postgresql.enable
  - name: filebeat
    version: 7.17.1
    repository: https://helm.elastic.co
    condition: deploy.filebeat.enable
  - name: contour
    version: 7.8.0
    repository: https://charts.bitnami.com/bitnami
    condition: deploy.contour.enable
maintainers:
  - name: Rafay
version: 0.0.1-alpha.3
appVersion: "v0.0.1"
