# Default values for rcloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Number of replicas in deployment
replicaCount: 1

images:
  rcloudBase:
    name: rcloud-base
    repository: registry.dev.rafay-edge.net/akshay196/rcloud-base
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  relay:
    name: relay
    repository: registry.dev.rafay-edge.net/akshay196/relay
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  prompt:
    name: prompt
    repository: registry.dev.rafay-edge.net/akshay196/prompt
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  rcloudConsoleUI:
    name: rcloud-console-ui
    repository: registry.dev.rafay-edge.net/akshay196/rcloud-console-ui
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  # If defined, a imagePullPolicy applied to all Rcloud deployments
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

services:
  rcloudBase:
    type: ClusterIP
    ports:
      - name: http
        port: 11000
      - name: rpc
        port: 10000
      - name: relay-peering
        port: 10001

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

kratos:
  enabled: true

elasticsearch:
  enabled: false

postgresql:
  enabled: false
