# Default values for rcloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of replicas in deployment
replicaCount: 1

# List of images to be deployed along with its tag. Specifying image
# tag overrides deault value which is chart appVersion.
images:
  rcloudBase:
    name: rcloud-base
    # -- rcloud base image
    repository: registry.dev.rafay-edge.net/akshay196/rcloud-base
    tag: ""
  rcloudBaseInit:
    name: rcloud-base-init
    # -- rcloud base initialize image
    repository: registry.dev.rafay-edge.net/akshay196-temp/rcloud-base-init
    tag: ""
  relay:
    name: relay
    # -- relay image
    repository: registry.dev.rafay-edge.net/akshay196/relay
    tag: ""
  prompt:
    name: prompt
    # -- prompt image
    repository: registry.dev.rafay-edge.net/akshay196/prompt
    tag: ""
  rcloudConsoleUI:
    name: rcloud-console-ui
    # -- rcloud console ui image
    repository: registry.dev.rafay-edge.net/akshay196-temp/rcloud-console-ui
    tag: ""

  # -- If defined, a imagePullPolicy applied to all deployments
  pullPolicy: IfNotPresent

# -- If defined, uses a Secret to pull an image from a private Docker
# registry or repository
imagePullSecrets: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is auto generated.
  name: ""

# -- Annotations for the all deployed pods
podAnnotations: {}

# Pod Security Context
podSecurityContext: {}
  # fsGroup: 2000

# Security Context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# List of services and their port numbers. When "port" is not
# specificed in "services.<name>.ports" list then service exposes on
# containerPort instead.
services:
  # -- rcloud base service config
  rcloudBase:
    type: ClusterIP
    ports:
      - name: http
        containerPort: 11000
      - name: rpc
        containerPort: 10000
      - name: relay-peering
        containerPort: 10001
  # -- prompt service config
  prompt:
    type: ClusterIP
    ports:
      - name: http
        containerPort: 7009
  # -- relay service config
  relay:
    type: ClusterIP
    ports:
      - name: https
        containerPort: 443
  # -- rcloud console service config
  rcloudConsoleUI:
    type: ClusterIP
    ports:
      - name: nginx
        containerPort: 80

ingress:
  # - install ingress resources.
  enabled: false
  className: ""
  # - Annotation for ingress resources. The ssl-passthrough annotation
  # - is mandatory for ZTKA ingress.
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- Ingress TLS for console
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Autoscale rcloud-base deployment resource
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

domain:
  # -- Host
  host: rafay.local
  # -- subdomain used for the console UI
  consoleSubdomain: "console"
  # -- a wildcard subdomain used for controller cluster to target
  # -- cluster communication
  coreConnectorSubdomain: "*.core-connector"
  # -- a wildcard subdomain used for controller cluster to end user
  # -- communication
  userSubdomain: "*.user"

rcloudBase:
  # -- Enable rcloud-base migrations
  automigrate: true
  initialize:
    # -- Partner name
    partner: "DefaultPartner"
    # -- Partner description
    partnerDesc: "Default Partner"
    # -- Partner host
    partnerHost: "rafay.local"
    # -- Organization name
    org: "DefaultOrg"
    # -- Organization description
    orgDesc: "Default Organization"
    # -- Admin email address
    adminEmail: "admin@rafay.local"
    # -- Admin first name
    adminFirstName: "Admin"
    # -- Admin last name
    adminLastName: "User"

deploy:
  kratos:
    # -- Kratos instance is auto deployed and managed by Helm release
    # when true.
    enable: true
    # -- SMTP connection URI that used by auto-deployed kratos for
    # sending mails for example, account recovery etc.
    smtpConnectionURI: "smtps://test:test@mypost:1025/?skip_ssl_verify=true"
    # -- Kratos public address. Required when `deploy.kratos.enable`
    # is unset
    publicAddr: ""
    # -- Kratos admin address. Required when `deploy.kratos.enable` is
    # unset
    adminAddr: ""

  elasticsearch:
    # -- Elasticsearch instance is auto deployed and managed by Helm
    # release when true.
    enable: false
    # -- Elasticsearch address. Required when `deploy.elasticsearch.enable`
    # is unset.
    address: ""

  postgresql:
    # -- Postgresql db is auto deployed and managed by Helm release
    # when true. (It is recommended to manage your own DB instance
    # separately or use DB services like Amazon RDS in production)
    enable: false
    # -- Postgresql address for example, "localhost:5432". Required
    # when `deploy.postgresql.enable` is unset
    address: ""
    # -- Postgresql username. Required when `deploy.postgresql.enable`
    # is unset.
    username: ""
    # -- Postgresql password. Required when `deploy.postgresql.enable`
    # is unset.
    password: ""
    # -- Postgresql database name. Required when
    # `deploy.postgresql.enable` is unset.
    database: ""

  filebeat:
    # -- Filebeat is used to collect audit logs into the system. You
    # can disable this if you don't want audit logs.
    enable: true
    # -- You can use this to config the index prefixes for
    # elasticsearch.  This has to match with your filebeat config in
    # `filebeat.daemonset.filebeatConfig.filebeat.yml`
    indexPrefix: "ralog"
    # TODO: can we somehow template it in filebeat.yml?

  contour:
    # -- auto install contour ingress controller
    enable: true

    # -- TLS properties of the virtual host
    tls: {}
    # secretName: chart-example-tls

# -- the chart will overwrite some values of kratos subchart.
# @default -- kratos subchart overwrite
kratos:
  secret:
    enabled: false
    nameOverride: "rcloud-kratos"
  kratos:
    development: false
    config:
      serve:
        public:
          cors:
            enabled: true
            allowed_headers:
              - Authorization
              - Cookie
              - Content-Type
              - X-Session-Token
            exposed_headers:
              - Content-Type
              - Set-Cookie
        admin:
          port: 4434
      selfservice:
        methods:
          password:
            enabled: true
          oidc:
            enabled: true
        flows:
          settings:
            privileged_session_max_age: 15m
          recovery:
            enabled: true
          registration:
            lifespan: 10m
            after:
              password:
                hooks:
                  - hook: session
              oidc:
                hooks:
                  - hook: session
      identity:
        default_schema_url: file:///etc/config/identity.default.schema.json

    identitySchemas:
      "identity.default.schema.json": |
        {
          "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
          "$schema": "http://json-schema.org/draft-07/schema#",
          "title": "Person",
          "type": "object",
          "properties": {
            "traits": {
              "type": "object",
              "properties": {
                "first_name": {
                  "title": "First name",
                  "type": "string",
                  "pattern": "^.*$"
                },
                "last_name": {
                  "title": "Last name",
                  "type": "string",
                  "pattern": "^.*$"
                },
                "description": {
                  "title": "Description",
                  "type": "string",
                  "pattern": "^.*$"
                },
                "email": {
                  "type": "string",
                  "format": "email",
                  "title": "E-Mail",
                  "minLength": 3,
                  "ory.sh/kratos": {
                    "credentials": {
                      "password": {
                        "identifier": true
                      }
                    },
                    "verification": {
                      "via": "email"
                    },
                    "recovery": {
                      "via": "email"
                    }
                  }
                },
                "idp_groups": {
                  "title": "IDP groups",
                  "type": "array",
                  "items": {
                      "type": "string"
                  }
                }
              },
              "required": [
                "first_name",
                "last_name",
                "description",
                "email"
              ],
              "additionalProperties": false
            }
          }
        }

  deployment:
    extraEnv:
      - name: SERVE_PUBLIC_BASE_URL
        valueFrom:
          configMapKeyRef:
            name: rcloud-kratos-config
            key: serve_public_base_url
      - name: SELFSERVICE_DEFAULT_BROWSER_RETURN_URL
        valueFrom:
          configMapKeyRef:
            name: rcloud-kratos-config
            key: default_browser_return_url
      - name: SELFSERVICE_WHITELISTED_RETURN_URLS
        valueFrom:
          configMapKeyRef:
            name: rcloud-kratos-config
            key: default_browser_return_url
      - name: SELFSERVICE_FLOWS_SETTINGS_UI_URL
        valueFrom:
          configMapKeyRef:
            name: rcloud-kratos-config
            key: selfservice_flows_settings_ui_url
      - name: SELFSERVICE_FLOWS_RECOVERY_UI_URL
        valueFrom:
          configMapKeyRef:
            name: rcloud-kratos-config
            key: selfservice_flows_recovery_ui_url
      - name: SELFSERVICE_FLOWS_REGISTRATION_UI_URL
        valueFrom:
          configMapKeyRef:
            name: rcloud-kratos-config
            key: selfservice_flows_registration_ui_url
    # OIDC Provider config synchronizer as sidecar to Kratos
    extraContainers: |
        - name: synchronizer
          image: "registry.dev.rafay-edge.net/akshay196-temp/kratos-synchronizer:v0.0.1"
          volumeMounts:
            - name: other-configs
              mountPath: /etc/kratos
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: rcloud-db
                  key: DSN
            - name: KRATOS_PROVIDER_CFG
              value: "/etc/kratos/providers.yaml"
    extraArgs:
      - --config
      - /etc/kratos/providers.yaml
    extraVolumes:
      - name: other-configs
        emptyDir: {}
    extraVolumeMounts:
      - name: other-configs
        mountPath: /etc/kratos
    extraInitContainers: |
        - name: create-file
          image: "busybox:latest"
          command: ['sh', '-c', 'touch /etc/kratos/providers.yaml']
          volumeMounts:
            - name: other-configs
              mountPath: /etc/kratos
  watcher:
    enabled: true
    mountFile: /etc/kratos/providers.yaml

elasticsearch:
  replicas: 1
  minimumMasterNodes: 1

postgresql:
  dbAddr: ""
  # -- When `deploy.postgresql.enable` is true postgres instance is
  # created with this credentials.
  auth:
    existingSecret: rcloud-postgresql
    enablePostgresUser: false
    username: "admindbuser"
    password: "admindbpassword"
    database: "admindb"

# -- the chart will overwrite some values of filebear subchart.
# @default -- filebeat subchart overwrite
filebeat:
  daemonset:
    filebeatConfig:
      filebeat.yml: |
        setup.ilm.enabled: false
        filebeat.module: {}
        filebeat.inputs: {}
        filebeat.autodiscover:
          providers:
            - type: kubernetes
              templates:
                - condition:
                    equals:
                      kubernetes.container.name: rcloud-tail
                  config:
                    - type: container
                      json.add_error_key: true
                      json.expand_keys: true
                      fields:
                        rcloud.component: system
                      processors:
                        - timestamp:
                            field: json.timestamp
                            layouts:
                              - "2006-01-02T15:04:05.999999999Z"
                            test:
                              - "2022-04-21T11:14:13.538105978Z"
                      paths:
                        - /var/log/containers/*-${data.kubernetes.container.id}.log
                - condition:
                    equals:
                      kubernetes.container.name: rcloud-prompt-tail
                  config:
                    - type: container
                      json.add_error_key: true
                      json.expand_keys: true
                      fields:
                        rcloud.component: prompt
                      processors:
                        - timestamp:
                            field: json.timestamp
                            layouts:
                              - "2006-01-02T15:04:05.999999999Z"
                            test:
                              - "2022-04-21T11:14:13.538105978Z"
                      paths:
                        - /var/log/containers/*-${data.kubernetes.container.id}.log
                - condition:
                    equals:
                      kubernetes.container.name: rcloud-relay-tail
                  config:
                    - type: container
                      json.add_error_key: true
                      json.expand_keys: true
                      fields:
                        rcloud.component: relay
                      processors:
                        - timestamp:
                            field: json.ts
                            layouts:
                              - "2006-01-02T15:04:05.999999999Z"
                            test:
                              - "2022-04-21T11:14:13.538105978Z"
                      paths:
                        - /var/log/containers/*-${data.kubernetes.container.id}.log

        processors:
          - add_cloud_metadata: ~
          - add_kubernetes_metadata:
              in_cluster: false

        output.file:
          enabled: false

        output.elasticsearch:
          index: "ralog-%{[fields.rcloud.component]}-%{+yyyy.MM.dd}"
          hosts: ['${ELASTICSEARCH_HOST:elasticsearch-master}:${ELASTICSEARCH_PORT:9200}']
          # username: ${ELASTICSEARCH_USERNAME} # uncomment this for username
          # password: ${ELASTICSEARCH_PASSWORD} # uncomment this for password

        setup:
          template:
            name: ralog-template
            overwrite: true
            pattern: ralog-*
            append_fields:
              - name: json.timestamp
                type: date
              - name: json.ts
                type: date

# -- the chart will overwrite some values of contour subchart.
# @default -- contour subchart overwrite
contour:
  contour:
    # HTTPProxy CR installation failed when CRDs are not present. To
    # install CRDs before chart installation we manage contour CRDs in
    # 'crds/' folder as a workaround, till we find better solution to
    # solve this.
    # https://github.com/RafayLabs/rcloud-helm/issues/13
    manageCRDs: false
    # Do not create IngressClass resource. We setup HTTPProxy
    # resources instead.
    ingressClass:
      create: false

  envoy:
    service:
      # -- Annotations for Envoy service.
      annotations: {}
