## This is an example values used to overwrite default values.yaml
## for deploying chart on AWS EKS cluster.
##
## contour on AWS with NLB: https://projectcontour.io/guides/deploy-aws-nlb/

## NOTE: Use along with `values.dev.yaml` if you are setting up a dev cluster

deploy:
  postgresql:
    enable: true

kratos:
  kratos:
    development: true

contour:
  envoy:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
