apiVersion: v1
kind: ConfigMap
metadata:
  name: rcloud-base-config
  labels:
    {{- include "rcloud.labels" . | nindent 4 }}
    {{- include "rcloud.selectorLabels" (dict "image" $.Values.images.rcloudBase "release" $.Release) | nindent 4 }}
data:
  DEV: "false"
  ES_END_POINT: {{ include "rcloud.esAddr" . | quote }}
  KRATOS_ADDR: {{ include "rcloud.kratosAddr" . | quote }}
  DB_ADDR: {{ include "rcloud.dbAddr" . | quote }}
  DB_USER: {{ .Values.postgresql.auth.username }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password }}
  DB_NAME: {{ .Values.postgresql.auth.database }}
  DSN: {{ include "rcloud.dsn" . | quote }}
  RELAY_IMAGE: {{ .Values.images.relay.repository }}:{{ .Values.images.relay.tag | default .Chart.AppVersion }}
