apiVersion: v1
kind: ConfigMap
metadata:
  name: rcloud-base-config
  labels:
    {{- include "rcloud.labels" . | nindent 4 }}
    {{- include "rcloud.selectorLabels" (dict "image" $.Values.images.rcloudBase "release" $.Release) | nindent 4 }}
data:
  DEV: "false"
  ES_END_POINT: {{ include "rcloud.esAddr" . | quote }}
  KRATOS_ADDR: {{ include "rcloud.kratos.adminAddr" . | quote }}
  KRATOS_PUB_ADDR: {{ include "rcloud.kratos.publicAddr" . | quote }}
  RELAY_IMAGE: {{ .Values.images.relay.repository }}:{{ .Values.images.relay.tag | default .Chart.AppVersion }}
  SCHEDULER_NAMESPACE: {{ .Release.Namespace | quote }}
  SENTRY_PEERING_HOST: "rcloud-base:10001"
  {{ if .Values.ingress.enabled -}}
  CORE_RELAY_CONNECTOR_HOST: "*.core-connector.ztka.{{ .Values.ingress.host }}:10002"
  CORE_RELAY_USER_HOST: "*.user.ztka.{{ .Values.ingress.host }}:10002"
  SENTRY_BOOTSTRAP_ADDR: "console.{{ .Values.ingress.host }}"
  {{ end }}
