apiVersion: apps/v1
kind: Deployment
metadata:
  name: prompt
  labels:
    {{- include "rcloud.labels" . | nindent 4 }}
    {{- include "rcloud.selectorLabels" (dict "image" $.Values.images.prompt "release" $.Release) | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rcloud.selectorLabels" (dict "image" $.Values.images.prompt "release" $.Release) | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rcloud.selectorLabels" (dict "image" $.Values.images.prompt "release" $.Release) | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rcloud.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: kubectl
          emptyDir: {}
        - name: rcloud-prompt-audit-logs
          emptyDir: {}
      initContainers:
        - name: install-kubectl
          image: busybox:latest
          volumeMounts:
            - name: kubectl
              mountPath: /data
          command: ['sh', '-c', 'wget -q "https://dl.k8s.io/release/$(wget -qO- https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -O /data/kubectl && chmod +x /data/kubectl']
      containers:
        - name: {{ .Chart.Name }}-prompt-tail
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "busybox:latest"
          command: ["tail", "-F", "/audit-logs/audit.log"]  # should the path be configurable?
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          volumeMounts:
            - name: rcloud-prompt-audit-logs
              mountPath: /audit-logs
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.prompt.repository }}:{{ .Values.images.prompt.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          envFrom:
          - configMapRef:
              name: prompt-config
          - secretRef:
              name: rcloud-db
          ports:
            {{- range .Values.services.prompt.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
            {{- end }}
          volumeMounts:
            - name: kubectl
              subPath: kubectl
              mountPath: /usr/local/bin/kubectl
            - name: rcloud-prompt-audit-logs
              mountPath: /audit-logs
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
