{{- if .Values.deploy.contour.enable -}}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: console
spec:
  virtualhost:
    fqdn: {{ include "rcloud.consoleFQDN" . | quote }}
    {{- with .Values.deploy.contour.tls }}
    tls:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  routes:
    - services:
      - name: rcloud-base
        port: 11000
      conditions:
      - prefix: /auth
    - services:
      - name: rcloud-base
        port: 11000
      conditions:
      - prefix: /event
    - services:
      - name: rcloud-base
        port: 11000
      conditions:
      - prefix: /infra
    - services:
      - name: rcloud-base
        port: 11000
      conditions:
      - prefix: /v2/sentry
    - services:
      - name: prompt
        port: 7009
      conditions:
      - prefix: /v2/debug/prompt
      enableWebsockets: true
    - services:
      - name: rcloud-console-ui
        port: 80
      conditions:
      - prefix: /
    - services:
      - name: myrelease-kratos-public
        port: 80
      conditions:
      - prefix: /self-service
{{- end -}}
