{{- if .Values.ingress.enabled -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{.Release.Name}}-{{.Chart.Name}}
  labels:
    {{- include "rcloud.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className}}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: rcloud-base
                port:
                  number: 11000
          - path: /event
            pathType: Prefix
            backend:
              service:
                name: rcloud-base
                port:
                  number: 11000
          - path: /infra
            pathType: Prefix
            backend:
              service:
                name: rcloud-base
                port:
                  number: 11000
          - path: /v2/sentry
            pathType: Prefix
            backend:
              service:
                name: rcloud-base
                port:
                  number: 11000
          - path: /v2/debug/prompt
            pathType: Prefix
            backend:
              service:
                name: prompt
                port:
                  number: 7009
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rcloud-console-ui
                port:
                  number: 80
{{- end }}
