apiVersion: v1
kind: Secret
metadata:
  name: rcloud-kratos
  labels:
    {{- include "rcloud.labels" . | nindent 4 }}
type: Opaque
data:
  dsn: {{ include "rcloud.dsn" . | b64enc | quote }}
  smtpConnectionURI: {{ "smtps://test:test@mailslurper:1025/?skip_ssl_verify=true" | b64enc }}
