{{- if .Values.deploy.postgresql.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: rcloud-postgresql
  labels:
    {{- include "rcloud.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
{{ end }}
