apiVersion: v1
kind: Service
metadata:
  name: prompt
  labels:
    {{- include "rcloud.labels" . | nindent 4 }}
    {{- include "rcloud.selectorLabels" (dict "image" $.Values.images.prompt "release" $.Release) | nindent 4 }}
spec:
  type: {{ .Values.services.prompt.type }}
  ports:
    {{- range .Values.services.prompt.ports }}
    - name: {{ .name }}
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .name }}
    {{- end }}
  selector:
    {{- include "rcloud.selectorLabels" (dict "image" $.Values.images.prompt "release" $.Release) | nindent 4 }}
