apiVersion: v1
kind: Service
metadata:
  name: rcloud-base
  labels:
    {{- include "rcloud.labels" . | nindent 4 }}
    {{- include "rcloud.selectorLabels" (dict "image" $.Values.images.rcloudBase "release" $.Release) | nindent 4 }}
spec:
  type: {{ .Values.services.rcloudBase.type }}
  ports:
    {{- range .Values.services.rcloudBase.ports }}
    - name: {{ .name }}
      protocol: TCP
      port: {{ .port | default .containerPort }}
      targetPort: {{ .name }}
    {{- end }}
  selector:
    {{- include "rcloud.selectorLabels" (dict "image" $.Values.images.rcloudBase "release" $.Release) | nindent 4 }}
