apiVersion: v1
kind: Service
metadata:
  name: relay-server
  labels:
    {{$data := dict "image" $.Values.images.relay "release" $.Release }}
    {{- include "rcloud.selectorLabels" $data | nindent 4 }}
spec:
  type: {{ .Values.services.relay.type }}
  ports:
    {{- range .Values.services.relay.ports }}
    - name: {{ .name }}
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .name }}
    {{- end }}
  selector:
    {{$data := dict "image" $.Values.images.relay "release" $.Release }}
    {{- include "rcloud.selectorLabels" $data | nindent 4 }}
